#ifndef __DMSCANNER_HPP__
#define __DMSCANNER_HPP__ 1
 
#if ! defined(yyFlexLexerOnce)
#include <FlexLexer.h>
#endif
 
#undef YY_DECL
#define YY_DECL \
DM::Parser::token_type \
DM::Lexer::lex( \
	DM::Parser::semantic_type* yylval, \
	DM::Parser::location_type* yylloc \
)
 
#include "parser.hpp"
namespace DM {
class Lexer : public yyFlexLexer
{
public:
	Lexer(std::istream *in) :
		yyFlexLexer(in),
		yylval( nullptr )
	{};
	/** This is the main lexing function. It is generated by flex according to
	* the macro declaration YY_DECL above. The generated bison parser then
	* calls this virtual function to fetch new tokens. */
    virtual Parser::token_type lex(Parser::semantic_type* yylval, Parser::location_type* yylloc);
	 
private:
	/* hide this one from public view */
	int yylex();
	/* yyval ptr */
	DM::Parser::semantic_type *yylval;
};
}
#endif